Hw 3
aka-Steam/E-commerce pull request #1
Opened 2024-11-04 15:14 UTC by aka-Steam

2024-11-07 14:01 UTC, nikkov13 requested changes

2024-11-07 14:01 UTC, nikkov13 commented on public/vite.svg
Если уже есть лого, можно поменять на него

2024-11-07 14:01 UTC, nikkov13 commented on src/assets/react.svg
Можно наверное дропнуть

2024-11-07 14:01 UTC, nikkov13 commented on src/components/Button/Button.module.scss
> +.button.loading:hover:not(.button:disabled, .button[disabled]) {
loading должно быть модификатором класса (`.button_loading`). Для лучшего понимания вложенности и чтобы не прописывать каждый раз корневой класс в файле стилей можно использовать &, например в данном случае 
```
.button {
  width: max-content;
  
  &:hover {
    ...
  }
  
  &_loading {
    ...
  }
}
```
Для однообразия корневой класс во всех компонентах можно называть `.root`, но это не крит

2024-11-07 14:01 UTC, nikkov13 commented on src/components/Button/Button.tsx
> +  /** Состояние загрузки */
Тут есть смысл еще className снаружи принимать для позиционирования

2024-11-07 14:01 UTC, nikkov13 commented on src/components/Button/Button.tsx
> +  };
Завернуть в useCallback

2024-11-07 14:01 UTC, nikkov13 commented on src/components/Loader/Loader.tsx
> +    color?: string;
Думаю лучше тут вынести цвета которые могут использоваться в енам например и управлять цветом лоадера через класс

2024-11-07 14:01 UTC, nikkov13 commented on src/components/Card/Card.tsx
> +  ...otherProps
Думаю otherProps тут лишнее

2024-11-07 14:01 UTC, nikkov13 commented on src/components/CheckBox/CheckBox.module.css
> +    width: "40px";
Не нужны кавычки, + можно сделать для этого миксин square, который будет задавать одинаковую ширину и высоту

2024-11-07 14:01 UTC, nikkov13 commented on src/components/CheckBox/CheckBox.module.css
> +.div {
Сделай классы по БЭМ и красиво как в компоненте `Card`, называть класс `.div` это прям плохая практика, абсолютно непонятно что это

2024-11-07 14:01 UTC, nikkov13 commented on src/components/CheckBox/CheckBox.module.css
> +.CheckBoxIcon{
Стараемся избегать заглавных в именах классов, можно разделять - или _

2024-11-07 14:01 UTC, nikkov13 commented on src/components/CheckBox/CheckBox.tsx
> +import styles from './CheckBox.module.css'
Стили всегда идут последним импортом

2024-11-07 14:01 UTC, nikkov13 commented on src/components/CheckBox/CheckBox.tsx
> +      }}
Это лучше сделать через класс модификатор

2024-11-07 14:01 UTC, nikkov13 commented on src/components/CheckBox/CheckBox.tsx
> +        className={`${className} ${styles.div} ${disabled ? styles.dis : ''}`}
Подключен classNames, давай через него собирать классы, + className всегда идет последним чтобы избежать проблем с переопределением стилей

2024-11-07 14:01 UTC, nikkov13 commented on src/components/CheckBox/CheckBox.tsx
> +          strokeOpacity={disabled ? "0.4" : "1"}
Это можно сделать просто через модификатор класса, чтобы не надо было задавать color через проп, в иконках все цвета надо проставить currentColor и управлять через цветом через css color

2024-11-07 14:01 UTC, nikkov13 commented on src/components/CheckBox/CheckBox.module.css
> +    height: "40px";
Не нужны кавычки и можно для этого сделать миксин square

2024-11-07 14:01 UTC, nikkov13 commented on src/components/CheckBox/CheckBox.module.css
> +.div {
Проименуй везде классы по БЭМ и сделай вложенность красиво как в компоненте `Card`, называть класс `.div` очень плохая практика, вообще непонятно что это

2024-11-07 14:01 UTC, nikkov13 commented on src/components/CheckBox/CheckBox.module.css
> +.CheckBoxIcon{
давай разделять не кэмэл кейсов слова в классах, а - или _ в зависимости от того, как отделяешь модификаторы

2024-11-07 14:01 UTC, nikkov13 commented on src/components/CheckBox/CheckBox.tsx
> +      }}
Это надо сделать через класс-модификатор `.root_disabled`

2024-11-07 14:01 UTC, nikkov13 commented on src/components/CheckBox/CheckBox.tsx
> +        onChange={(e) => onChange(e.target.checked)}
Это надо вынести в useCallback

2024-11-07 14:01 UTC, nikkov13 commented on src/components/CheckBox/CheckBox.tsx
> +        className={`${className} ${styles.div} ${disabled ? styles.dis : ''}`}
Давай собирать классы через classnames, + className всегда идет последним чтобы не было проблем при переопределении стилей сверху

2024-11-07 14:01 UTC, nikkov13 commented on src/components/CheckBox/CheckBox.tsx
> +          strokeOpacity={disabled ? "0.4" : "1"}
Это надо через класс сделать, чтобы удобно управлять цветом иконок через css, надо в svg проставить цвет currentColor в fill, stroke итд

2024-11-07 14:01 UTC, nikkov13 commented on src/components/Header/Header.module.scss
> +}
Лучше это вложить в header, чтобы удобнее было читать, + можно завести переменные и миксины для основных брейкпоинтов

2024-11-07 14:01 UTC, nikkov13 commented on src/components/Header/Header.module.scss
> +.navContainer{
Везде проименовать классы по БЭМ и сделать вложенность как в компоненте `Card`

2024-11-07 14:01 UTC, nikkov13 commented on src/components/Header/Header.module.scss
> +    transition: .3s;
Можно завести миксин для transition с дефолтным временем и функцией времени и прокидывать туда только анимируемое свойство

2024-11-07 14:01 UTC, nikkov13 commented on src/components/Header/Header.tsx
> +          d="M16.7272 19.384C15.3512 19.384 14.2552 19.048 13.4392 18.376C12.6392 17.704 12.2393 16.792 12.2393 15.64C12.2393 14.536 12.6153 13.624 13.3673 12.904C14.1193 12.184 15.2472 11.704 16.751
Свг надо вынести в отдельный компонент / файл, а то компонент становится нечитаемым

2024-11-07 14:01 UTC, nikkov13 commented on src/components/Header/Header.tsx
> +      <Link className={styles.navLink} to="/">About us</Link>
Можно вынести в конфиг массив { url, title }[] и тут мапить его чтобы не писать однотипный код

2024-11-07 14:01 UTC, nikkov13 commented on src/components/Header/Header.tsx
> +      <div className={styles.iconStub}></div>
Поставь тогда сразу кнопки-иконки а потом просто обработчики доделать

2024-11-07 14:01 UTC, nikkov13 commented on src/components/Loader/Loader.module.scss
> +    border-right: 5px solid $loader-bg;
Проще сделать border: 5px solid $loader-bg; border-bottom: 5px solid rgba(0, 0, 0, 0);
А еще проще svg

2024-11-07 14:01 UTC, nikkov13 commented on src/components/Loader/Loader.module.scss
> +.loaderContainer.s {
Это должно быть модификатором .loader_s и не нужна избыточная специфичность

2024-11-07 14:01 UTC, nikkov13 commented on src/components/Loader/Loader.module.scss
> +}
Можно без >

2024-11-07 14:01 UTC, nikkov13 commented on src/components/MultiDropdown/MultiDropdown.tsx
> +};
Можно типы в отдельный файл ./types.ts вынести

2024-11-07 14:01 UTC, nikkov13 commented on src/components/MultiDropdown/MultiDropdown.tsx
> +  };
Функции давай в useCallback заворачивать чтобы не было лишних рендеров дочерних компонентов

2024-11-07 14:01 UTC, nikkov13 commented on src/components/Pagination/Pagination.module.scss
> +.pagination{
пробелы перед { пропущены

2024-11-07 14:01 UTC, nikkov13 commented on src/components/Pagination/Pagination.module.scss
> +    color:#FFFFFF;
Все цвета в переменных

2024-11-07 14:01 UTC, nikkov13 commented on src/components/Pagination/Pagination.tsx
> +        onClick={() => onPageChange(currentPage - 1)}
В useCallback

2024-11-07 14:01 UTC, nikkov13 commented on src/components/Pagination/Pagination.tsx
> +        </svg>
Все svg в компоненты иконок вынести

2024-11-07 14:01 UTC, nikkov13 commented on src/components/Pagination/Pagination.tsx
> +        }}
Через класс давай

2024-11-07 14:01 UTC, nikkov13 commented on src/components/Pagination/Pagination.tsx
> +              onClick={() => onPageChange(page)}
Если так прокидывать функции, они создаются новые при каждом рендере Pagination, соответственно ссылка меняется и дочерний компонент перерендеривается

2024-11-07 14:01 UTC, nikkov13 commented on src/components/Pagination/Pagination.tsx
> +        }}
Через класс

2024-11-07 14:01 UTC, nikkov13 commented on src/components/Text/Text.module.scss
> +    font-weight: 400;
Шрифт можно в styles.css задать, а font-weight и так будет по дефолту 400

2024-11-07 14:01 UTC, nikkov13 commented on src/components/icons/ArrowDownIcon/ArrowDownIcon.tsx
> +                fill="inherit"
Вот тут currentColor

2024-11-07 14:01 UTC, nikkov13 commented on src/components/icons/CheckIcon/CheckIcon.tsx
> +            <path d="M4 11.6129L9.87755 18L20 7" stroke="inherit" strokeWidth="2" />
И тут currentColor

2024-11-07 14:01 UTC, nikkov13 commented on src/components/icons/Icon/Icon.tsx
> +    });
Это лишнее, надо просто currentColor в svg и через css ставить цвет

2024-11-07 14:01 UTC, nikkov13 commented on src/components/icons/Icon/Icon.tsx
> +    }
Лишнее

2024-11-07 14:01 UTC, nikkov13 commented on src/components/icons/Icon/Icon.tsx
> +    color?: 'primary' | 'secondary' | 'accent';
Лишнее

2024-11-07 14:01 UTC, nikkov13 commented on src/components/icons/Icon/Icon.tsx
> +            viewBox="0 0 24 24"
Вот viewBox лучше сверху передавать для каждой иконки свой, а то что-то где-то может обрезаться

2024-11-07 14:01 UTC, nikkov13 commented on src/pages/OneProductPage/OneProductPage.tsx
> +import Card from 'components/Card';
Сначала абсолютные импорты, потом относительные, в самом конце стили

2024-11-07 14:01 UTC, nikkov13 commented on src/pages/OneProductPage/OneProductPage.tsx
> +};
Типы лучше в отдельный файл рядом

2024-11-07 14:01 UTC, nikkov13 commented on src/pages/OneProductPage/OneProductPage.tsx
> +  const apiUrl: string = import.meta.env.VITE_API_URL + '/products/' + id;
Можно создать инстанс axios и подставить в него base url чтобы кажый раз руками не склеивать эндпоинты, для подстановки id использовать шаблонные строки `/products/${id}`

2024-11-07 14:01 UTC, nikkov13 commented on src/pages/OneProductPage/OneProductPage.tsx
> +        url: import.meta.env.VITE_API_URL + '/products/?limit=3&offset=12',
параметры запроса через params можно передавать чтобы было более читаемо и удобно

2024-11-07 14:01 UTC, nikkov13 commented on src/pages/OneProductPage/OneProductPage.tsx
> +        result.data.map((p: { id: any; description: any; images: any; price: any; title: any; category: { name: any; }; }) => ({
Надо тип вынести

2024-11-07 14:01 UTC, nikkov13 commented on src/pages/OneProductPage/OneProductPage.tsx
> +  const [RELATED_ITEMS, setRelatedItems] = useState<ProductInfo[]>([]);
Капсом только константы называем, это переменные

2024-11-07 14:01 UTC, nikkov13 commented on src/pages/OneProductPage/OneProductPage.tsx
> +            const imageSrc = product.images ? product.images[0].match(/https?:\/\/[^\s"]+/) : 'src/assets/noimage.png';
Это надо делать при нормализации сразу после fetch, а здесь только отрисовывать карточки

2024-11-07 14:01 UTC, nikkov13 commented on src/pages/OneProductPage/OneProductPage.tsx
> +                onClick={() => navigate(`/products/${product.id}`)}
В коллбэк

2024-11-07 14:01 UTC, nikkov13 commented on src/pages/OneProductPage/components/BackButton/BackButton.tsx
> +    className={`${s.backButton} ${className}`}
classnames, везде поправить

2024-11-07 14:01 UTC, nikkov13 commented on src/pages/OneProductPage/components/BackButton/BackButton.tsx
> +      </svg>
Все свг в иконки

2024-11-07 14:01 UTC, nikkov13 commented on src/pages/OneProductPage/components/Carousel/Carousel.tsx
> +      <img className={s.caruoselImage} src={source? source[0] : '\\src\\assets\\noimage.png'} alt={alter} />
ссылку не так вставляем, а через импорт

2024-11-07 14:01 UTC, nikkov13 commented on src/pages/ProductsPage/ProductsPage.tsx
> +  ];
Вынести из компонента, чтобы не пересоздавался массив, может вызывать ререндеры дочерних компонентов

2024-11-07 14:01 UTC, nikkov13 commented on src/pages/ProductsPage/ProductsPage.tsx
> +        <Text className={s.title} view={'title'}>
view="title" без скобок

2024-11-10 14:41 UTC, aka-Steam commented
Все 59 правок внесены

2024-11-15 10:46 UTC, nikkov13 approved these changes

2024-11-15 10:46 UTC, nikkov13 commented on src/components/Header/Header.module.scss
> +    @media (max-width: 768px) {
лучше вынести брейкпоинты в переменные

2024-11-15 10:46 UTC, nikkov13 commented on src/components/Header/Header.tsx
> +          </Link>
Можно использовать NavLink, там есть возможность из коробки отслеживать активную страницу

2024-11-15 10:46 UTC, nikkov13 commented on src/components/Loader/Loader.tsx
> +    </svg>
А че это не вынести в иконку и завернуть в Icon

2024-11-15 10:46 UTC, nikkov13 commented on src/pages/OneProductPage/OnePoductPage.module.scss
> +    padding: $general-padding-lg $general-padding-xl $general-padding-xl $general-padding-xl;
Можно сделать более читаемо
```
padding: $general-padding-xl;
padding-top: $general-padding-lg;
```

2024-11-15 10:46 UTC, nikkov13 commented on src/pages/OneProductPage/OnePoductPage.module.scss
> +    &__description {
main {
 &__back {}
 &__product-info {}
итд

2024-11-15 10:46 UTC, nikkov13 commented on src/pages/OneProductPage/components/Carousel/Carousel.module.scss
> +    }
занести внуть
```
&__control {
  &:hover {}
}
```

2024-11-15 10:46 UTC, nikkov13 commented on src/pages/ProductsPage/ProductsPage.module.scss
> +    margin-bottom: $space-xxs;
main, main__title-container main__title итд

2024-11-15 16:17 UTC, merged